# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "CB5msSbnae82d78cFP6+03N7zjsJ0K/lXgDJvlYggmSh9Y8lhR0G0tzkL7OfQfrSaSSD+wSVlsPgBDd4ou+Crn7anlkh9tOZNcKHMPLqwEhDHvmGEDIwkkii3u0Y7VbnbWvazuJo1j4rXqP0gzKux2XPtv5aryoA6NBeEMEYv3G6A30VwzibyODdCmNpqAMVPjKjgBvLH7Kqb9JAnWo0MJvHNrJIEUYKK2J26T5z8gV8xrlGZMtUIcmFnohafyDRY6jS/69B7RDTlIGoAbTvMzZAxVAAHmQ4MX+2i5wBaRVGFW49rRBWaym/eMRBnJQ5Ys/Gy6rmoTcjhBgqYTbtMvKOfZegGTRtvCRXebV/v6GI+4edQ39D1/p71uWgycVeKsb/S2XOutoAPRlCQr2uZoJcO7NgfXXIEj35G5Xw2gflTd/E/KSN8p0MmDC2cRJ29KvP7Rm+8cFn2+fpWMgd3i+6Gpk5/YDPtkfo5STszkEboHWGr1WK64zwwyG+yYemrl7bc6jCSeYZITdiUGmqYUQHpuDtH7m8nxCZ99mkZxAFmRNkpRuI++JEODS+CCLetkW1MXtXT+C/ogUkquB+WRVBIbohELv544RD2eARVHiekYvUWnIUlRtwm13qmT8VW0xAd8arS5D3/vEiM+dMFDC1eEa7JmeOBJE4SA3BQN0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml